### ISSUE TITLE
Data laden: niet nodig?

### ISSUE THREAD

**Issue by vankesteren** [ImkeDekkers/Buurtvergelijker#4]
Ik heb het even gecheckt.. Volgens mij hebben jullie deze regels helemaal niet nodig?

https://github.com/ImkeDekkers/Buurtvergelijker/blob/65fc36038da6f35132477adb852457e88f10d3a9/Shiny_app/server.R#L11-L13

**Comment by pkwooning** [comment]
App also runs without these lines of code. Therefore deleted
